export const TOP_MENU_LIST = [
  { id: 1, name: '상품권', path: '/' },
  { id: 2, name: '주문/배송', path: '/' },
  { id: 3, name: '쿠폰/머니', path: '/' },
  { id: 4, name: '이벤트', path: '/' },
];

export const NAV_MENU_LIST = [
  { id: 1, name: '명함', path: '/', isNew: true },
  { id: 2, name: '스티커', path: '/sticker', isNew: false },
  { id: 3, name: '어패럴', path: '/apparel', isNew: true },
  { id: 4, name: '배너/현수막', path: '/banner', isNew: false },
  { id: 5, name: '사인/포스터', path: '/signs-posters', isNew: false },
  { id: 6, name: '홍보물', path: '/pr', isNew: false },
  { id: 7, name: '봉투/쇼핑백', path: '/packaging', isNew: false },
  { id: 8, name: 'MD', path: '/md', isNew: true },
  { id: 9, name: '카드', path: '/card', isNew: false },
  { id: 10, name: '캘린더', path: '/calendar-desk', isNew: false },
  { id: 11, name: '액세서리', path: '/accessory', isNew: false },
];

// 기준 페이지 네트워크 탭에서 불러와지는 group 데이터에 데이터 추가
export const NAV_MENU_GROUP = [
  { menuId: 1, name: '표준사이즈', value: '101', attr: 'BUSINESS_CARD', isNew: false, category: '사이즈' },
  { menuId: 1, name: 'OPM사이즈', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '사이즈' },
  { menuId: 1, name: '정사각사이즈', value: '101', attr: 'BUSINESS_CARD', isNew: false, category: '사이즈' },
  { menuId: 1, name: '소프트', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '프리미엄 소프트', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '프리미엄 매트', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '오리지널', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '럭스', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '리넨', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '펠트', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '펄', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '크라프트', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '투명', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: false, category: '용지' },
  { menuId: 1, name: '매트블랙', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: true, category: '용지' },
  { menuId: 1, name: '리사이클', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: true, category: '용지' },
  { menuId: 1, name: '박', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: true, category: '효과' },
  { menuId: 1, name: '형압', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: true, category: '효과' },
  { menuId: 1, name: '스코딕스', value: '107', attr: 'TRANS_BUSINESS_CARD', isNew: true, category: '효과' },
  { menuId: 2, name: '낱장', value: '102', attr: 'CARD', isNew: false, category: '형태' },
  { menuId: 2, name: 'DIY', value: '105', attr: 'POSTER', isNew: false, category: '형태' },
  { menuId: 2, name: '원형', value: '104', attr: 'STICKER', isNew: false, category: '형태' },
  { menuId: 2, name: '정사각형', value: '106', attr: 'STICKER_2ND', isNew: false, category: '형태' },
  { menuId: 2, name: '직사각형', value: '102', attr: 'CARD', isNew: false, category: '형태' },
  { menuId: 2, name: '와이드형', value: '105', attr: 'POSTER', isNew: false, category: '형태' },
  { menuId: 2, name: '롤스티커', value: '104', attr: 'STICKER', isNew: false, category: '형태' },
  { menuId: 2, name: '컬러 데칼', value: '106', attr: 'STICKER_2ND', isNew: true, category: '형태' },
  { menuId: 2, name: '그래픽 데칼', value: '106', attr: 'STICKER_2ND', isNew: true, category: '형태' },
  { menuId: 2, name: '스탠다드', value: '106', attr: 'STICKER_2ND', isNew: false, category: '용지' },
  {
    menuId: 2,
    name: '리무버블',
    value: '108',
    attr: 'COLOR_DECAL_STICKER',
    isNew: false,
    category: '용지',
  },
  {
    menuId: 2,
    name: '소프트',
    value: '109',
    attr: 'GRAPHIC_DECAL_STICKER',
    isNew: false,
    category: '용지',
  },
  { menuId: 2, name: '매트', value: '106', attr: 'STICKER_2ND', isNew: false, category: '용지' },
  { menuId: 2, name: '투명', value: '106', attr: 'STICKER_2ND', isNew: false, category: '용지' },
  { menuId: 2, name: '홀로그램', value: '106', attr: 'STICKER_2ND', isNew: false, category: '용지' },
  { menuId: 2, name: '크라프트', value: '106', attr: 'STICKER_2ND', isNew: false, category: '용지' },
  { menuId: 3, name: '반팔 티셔츠', value: '201', attr: 'FLYER', isNew: false, category: '상품' },
  { menuId: 3, name: '긴팔 티셔츠', value: '202', attr: 'BROCHURE', isNew: false, category: '상품' },
  { menuId: 3, name: '맨투맨/후드/집업', value: '203', attr: 'MENU', isNew: false, category: '상품' },
  { menuId: 3, name: '바지', value: '204', attr: 'POSTCARD', isNew: false, category: '상품' },
  { menuId: 3, name: '에코백', value: '205', attr: 'COUPON', isNew: false, category: '상품' },
  { menuId: 3, name: '파우치', value: '301', attr: 'PLACARD_BANNER', isNew: false, category: '상품' },
  { menuId: 3, name: '여성', value: '301', attr: 'PLACARD_BANNER', isNew: false, category: '성별' },
  { menuId: 3, name: '남성', value: '301', attr: 'PLACARD_BANNER', isNew: false, category: '성별' },
  { menuId: 3, name: '유아동', value: '301', attr: 'PLACARD_BANNER', isNew: false, category: '성별' },
  { menuId: 4, name: '현수막', value: '311', attr: 'STANDARD_BANNER', isNew: false, category: '' },
  { menuId: 4, name: '스탠다드 배너', value: '311', attr: 'STANDARD_BANNER', isNew: false, category: '' },
  { menuId: 4, name: '양면 배너', value: '312', attr: 'DOUBLE_SIDE_BANNER', isNew: false, category: '' },
  { menuId: 4, name: '롤업 배너', value: '314', attr: 'ROLLUP_BANNER', isNew: false, category: '' },
  { menuId: 4, name: '미니 배너', value: '313', attr: 'MINI_BANNER', isNew: false, category: '' },
  { menuId: 5, name: '보드 사인', value: '303', attr: 'BOARD_SIGN', isNew: false, category: '' },
  { menuId: 5, name: '아크릴 사인', value: '304', attr: 'ACRYLIC_SIGN', isNew: false, category: '' },
  { menuId: 5, name: '메탈 사인', value: '305', attr: 'METAL_SIGN', isNew: false, category: '' },
  { menuId: 5, name: '원목 사인', value: '306', attr: 'WOODEN_FRAME_SIGN', isNew: false, category: '' },
  { menuId: 5, name: '테이블탑 사인', value: '308', attr: 'TABLE_TOP_SIGN', isNew: false, category: '' },
  { menuId: 5, name: '카 마그넷', value: '309', attr: 'CAR_MAGNET', isNew: false, category: '' },
  { menuId: 5, name: 'A 프레임 사인', value: '310', attr: 'A_FRAME_SIGN', isNew: false, category: '' },

  { menuId: 8, name: '스마트톡', value: '501', attr: 'SMART_TOK', isNew: false, category: '데코' },
  { menuId: 8, name: '핀버튼', value: '502', attr: 'PIN_BUTTON', isNew: false, category: '데코' },
  { menuId: 8, name: '거울버튼', value: '503', attr: 'MIRROR_BUTTON', isNew: false, category: '데코' },
  { menuId: 8, name: '자석버튼', value: '504', attr: 'MAGNET_BUTTON', isNew: false, category: '데코' },
  { menuId: 8, name: '아크릴키링', value: '505', attr: 'ACRYLIC_KEYRING', isNew: false, category: '데코' },

  { menuId: 10, name: '캘린더', value: '401', attr: 'CALENDAR_DESK', isNew: false, category: '' },
  { menuId: 7, name: '봉투', value: '601', attr: 'ENVELOPE', isNew: false, category: '' },
  { menuId: 7, name: '쇼핑백', value: '602', attr: 'SHOPPINGBAG', isNew: false, category: '' },
  { menuId: 8, name: '스탠다드 볼펜', value: '508', attr: 'STANDARD_PEN', isNew: false, category: '문구' },
  { menuId: 8, name: '베이직 볼펜', value: '509', attr: 'BASIC_PEN', isNew: false, category: '문구' },
  { menuId: 8, name: '투명PVC커버 다이어리', value: '510', attr: 'PVC_DIARY', isNew: false, category: '문구' },
  { menuId: 8, name: '소프트커버 다이어리', value: '512', attr: 'SOFT_DIARY', isNew: false, category: '문구' },
  { menuId: 8, name: '하드커버 다이어리', value: '511', attr: 'HARD_DIARY', isNew: false, category: '문구' },
  { menuId: 8, name: '메모패드', value: '513', attr: 'MEMO_PAD', isNew: false, category: '문구' },
  { menuId: 8, name: '노트패드', value: '514', attr: 'NOTE_PAD', isNew: false, category: '문구' },
  { menuId: 8, name: '스트레이트 글라스', value: '515', attr: 'STRAIGHT_GLASS', isNew: true, category: '컵/텀블러' },
  { menuId: 8, name: '리유저블 컵', value: '516', attr: 'REUSABLE_CUP', isNew: false, category: '컵/텀블러' },
  { menuId: 8, name: '에코 텀블러', value: '517', attr: 'ECO_TUMBLER', isNew: false, category: '컵/텀블러' },
  { menuId: 8, name: '라이트 볼펜', value: '518', attr: 'LIGHT_PEN', isNew: true, category: '문구' },
  { menuId: 8, name: '친환경 볼펜', value: '519', attr: 'ECO_PEN', isNew: true, category: '문구' },

  { menuId: 11, name: '액세서리', value: '901', attr: 'ACCESSORY', isNew: false, category: '사이즈' },
];
