export const TEMPLATE_LIST = [
  {
    templateCode: '01',
    templateName: '굿 컴퍼니',
    templateDescription: '기본 도형과 이니셜을 사용하여 누구나 손쉽게 사용할 수 있는 레이아웃입니다.',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '01', imgURL: '/template/굿 컴퍼니/image01.png', designCode: '001' },
      { itemType: 'BACK', templateCode: '01', imgURL: '/template/굿 컴퍼니/image02.png', designCode: '002' },
      { itemType: 'BACK', templateCode: '01', imgURL: '/template/굿 컴퍼니/image03.png', designCode: '003' },
      { itemType: 'BACK', templateCode: '01', imgURL: '/template/굿 컴퍼니/image04.png', designCode: '004' },
    ],
  },
  {
    templateCode: '02',
    templateName: '비장의 카드',
    templateDescription: '유니크한 디자인으로 금융업종에서 사용해 보세요. 유쾌함을 동시에 전달할 수 있을 거예요',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '02', imgURL: '/template/비장의 카드/image01.png', designCode: '005' },
      { itemType: 'BACK', templateCode: '02', imgURL: '/template/비장의 카드/image02.png', designCode: '006' },
      { itemType: 'BACK', templateCode: '02', imgURL: '/template/비장의 카드/image03.png', designCode: '007' },
      { itemType: 'BACK', templateCode: '02', imgURL: '/template/비장의 카드/image04.png', designCode: '008' },
    ],
  },
  {
    templateCode: '03',
    templateName: '창',
    templateDescription: '창을 통해 바라본 새로운 시각으로 더 좋은 집과 더 좋은 풍경을 만나보세요',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '03', imgURL: '/template/창/image01.png', designCode: '009' },
      { itemType: 'BACK', templateCode: '03', imgURL: '/template/창/image02.png', designCode: '010' },
      { itemType: 'BACK', templateCode: '03', imgURL: '/template/창/image03.png', designCode: '011' },
      { itemType: 'BACK', templateCode: '03', imgURL: '/template/창/image04.png', designCode: '012' },
    ],
  },
  {
    templateCode: '04',
    templateName: '창가 자리 주세요',
    templateDescription: '비행기 창문 모양에 비치는 각국의 일러스트레이션을 만나보세요',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '04', imgURL: '/template/창가 자리 주세요/image01.png', designCode: '013' },
      { itemType: 'BACK', templateCode: '04', imgURL: '/template/창가 자리 주세요/image02.png', designCode: '014' },
      { itemType: 'BACK', templateCode: '04', imgURL: '/template/창가 자리 주세요/image03.png', designCode: '015' },
      { itemType: 'BACK', templateCode: '04', imgURL: '/template/창가 자리 주세요/image04.png', designCode: '016' },
      { itemType: 'BACK', templateCode: '04', imgURL: '/template/창가 자리 주세요/image05.png', designCode: '017' },
    ],
  },
  {
    templateCode: '05',
    templateName: 'Build Trust',
    templateDescription: '간결하고 정직한 디자인으로 나에 대한 신뢰감을 전달해 보세요.',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '05', imgURL: '/template/Build Trust/image01.png', designCode: '018' },
      { itemType: 'BACK', templateCode: '05', imgURL: '/template/Build Trust/image02.png', designCode: '019' },
      { itemType: 'BACK', templateCode: '05', imgURL: '/template/Build Trust/image03.png', designCode: '020' },
      { itemType: 'BACK', templateCode: '05', imgURL: '/template/Build Trust/image04.png', designCode: '021' },
    ],
  },
  {
    templateCode: '06',
    templateName: 'Hello Children!',
    templateDescription: '알록달록한 도형과 자유로운 글자로 당신의 이야기를 담아보세요',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '06', imgURL: '/template/Hello Children!/image01.png', designCode: '022' },
      { itemType: 'BACK', templateCode: '06', imgURL: '/template/Hello Children!/image02.png', designCode: '023' },
      { itemType: 'BACK', templateCode: '06', imgURL: '/template/Hello Children!/image03.png', designCode: '024' },
      { itemType: 'BACK', templateCode: '06', imgURL: '/template/Hello Children!/image04.png', designCode: '025' },
    ],
  },
  {
    templateCode: '07',
    templateName: 'in스타강사',
    templateDescription: '자신의 프로필을 깔끔하고 눈에 띄게 표현보세요.',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '07', imgURL: '/template/in스타강사/image01.png', designCode: '026' },
      { itemType: 'BACK', templateCode: '07', imgURL: '/template/in스타강사/image02.png', designCode: '027' },
      { itemType: 'BACK', templateCode: '07', imgURL: '/template/in스타강사/image03.png', designCode: '028' },
      { itemType: 'BACK', templateCode: '07', imgURL: '/template/in스타강사/image04.png', designCode: '029' },
    ],
  },
  {
    templateCode: '08',
    templateName: 'OPM COMPANY',
    templateDescription: '단정한 기본 도형을 사용한 레이아웃으로 신뢰감을 전달합니다',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '08', imgURL: '/template/OPM COMPANY/image01.png', designCode: '030' },
      { itemType: 'BACK', templateCode: '08', imgURL: '/template/OPM COMPANY/image02.png', designCode: '031' },
      { itemType: 'BACK', templateCode: '08', imgURL: '/template/OPM COMPANY/image03.png', designCode: '032' },
      { itemType: 'BACK', templateCode: '08', imgURL: '/template/OPM COMPANY/image04.png', designCode: '033' },
    ],
  },
  {
    templateCode: '09',
    templateName: 'Researcher',
    templateDescription: '연구 관련 직군 등에서 연상되는 컬러와 아이콘을 배치하여 심플함을 강조합니다',
    templateProduct: '정사각사이즈 명함',
    templateOption: '소프트 / 직각 모서리',
    price: 2900,
    designList: [
      { itemType: 'FRONT', templateCode: '09', imgURL: '/template/Researcher/image01.png', designCode: '034' },
      { itemType: 'BACK', templateCode: '09', imgURL: '/template/Researcher/image02.png', designCode: '035' },
      { itemType: 'BACK', templateCode: '09', imgURL: '/template/Researcher/image03.png', designCode: '036' },
      { itemType: 'BACK', templateCode: '09', imgURL: '/template/Researcher/image04.png', designCode: '037' },
    ],
  },
];
